#!/bin/bash

image=liriorg/ostree-upload
curdir=$(readlink -f `dirname $0`)

echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
docker build -f ${curdir}/Dockefile -t $image . && docker push $image
